import { IconifyIcon } from '@iconify/react'

export type IconifyProps = IconifyIcon | string

export enum Icons {
  SYNC = 'material-symbols:sync',
  SEARCH = 'material-symbols:search',
  SEARCH_CHAT = 'lets-icons:chat-search-duotone',
  CLOSE = 'lets-icons:close-ring-duotone',
  PLUS = 'mdi:plus',
  EDIT = 'tabler:edit',
  TRASH = 'solar:trash-bin-trash-bold-duotone',
  SEND = 'lets-icons:send-duotone',
  FILE = 'solar:file-bold-duotone',
  EYE = 'solar:eye-bold-duotone',
  VISIBILITY = 'material-symbols:visibility-outline',
  ARROW_UP = 'iconamoon:arrow-up-2',
  ARROW_DOWN = 'iconamoon:arrow-down-2',
  ARROW_FLOW = 'fluent:arrow-flow-up-right-16-filled',
  CHECK = 'material-symbols:check',
  CANCEL = 'tabler:cancel',
  SAVE = 'prime:save',
  CHECKED = 'ep:checked',
  INFO = 'mdi:information',
  PIE = 'mingcute:chart-pie-2-fill',
  EMAIL_UNREAD = 'material-symbols:mark-email-unread',
  HISTORY = 'lucide:history',
  NEXT = 'grommet-icons:link-next',
  PREVIOUS = 'grommet-icons:link-previous',
  VERIFY = 'bitcoin-icons:verify-outline',
  LINK_BOTTOM = 'grommet-icons:link-bottom',
  LINK_TOP = 'grommet-icons:link-top',
  LINK_UP = 'nimbus:download',
  ADD = 'lets-icons:add-round',
  LIMPIAR = 'mdi:trash',
  EDITAR = 'tdesign:edit',
  REQUEST = 'material-symbols:clinical-notes-outline-rounded',
  PATH = 'material-symbols:conversion-path',
  TIMELINE = 'material-symbols:timeline',
  SUBDIRECTORY = 'ic:outline-subdirectory-arrow-right',

  REAL_ARROW_RIGHT = 'iconamoon:arrow-right-1',
  ARROW_RIGHT = 'iconamoon:arrow-right-2',
  ARROW_LEFT = 'iconamoon:arrow-left-1',
  CHEVRON_LEFT = 'ic:round-chevron-left',
  CHEVRON_RIGHT = 'ic:round-chevron-right',
  UNDO = 'prime:undo',
  LOGIN = 'ic:baseline-login',
  INSTAGRAM = 'ri:instagram-line',
  TIKTOK = 'ic:twotone-tiktok',
  TWITTER = 'hugeicons:new-twitter',
  FACEBOOK = 'uil:facebook',
  YOUTUBE = 'ri:youtube-fill',
  WHATSAPP = 'ic:round-whatsapp',
  EMAIL = 'ic:outline-email',
  PHONE = 'uil:phone',
  LOCATION = 'carbon:location',
  COPY = 'ic:baseline-content-copy',
  WARNING = 'ion:warning-outline',
  ERROR = 'hugeicons:danger',
  DRAG = 'icon-park-outline:drag',
  SETTINGS_OUTLINED = 'material-symbols:settings-outline-rounded',
  SORT = 'prime:sort-numeric-down',
  DESCARGAR = 'material-symbols:download-2-outline-rounded',
  CLEAN = 'carbon:clean',
  TUNE = 'ic:baseline-tune',
  TOKEN = 'iconoir:cube-hole',
  TOGGGLE_ON = 'ic:outline-toggle-on',
  TOGGLE_OFF = 'ic:outline-toggle-off',
  CHECK_LIST = 'si:ai-checklist-duotone',
  PLAY = 'zondicons:play-outline',
  DOWNLOAD = 'material-symbols:download-rounded',
  SAFE = 'si:shield-health-safety-duotone',
  PUBLICADOR = 'material-symbols:published-with-changes',
  CONSUMIDOR = 'fluent:server-link-20-filled',
  CHECK_LIST_2 = 'mdi:list-status',

  ADD_ENTITY = 'material-symbols:add-home-work-outline',
  CREATE = 'gridicons:create',
  SETTINGS = 'material-symbols:settings-rounded',
  PUBLISH = 'material-symbols:publish',
  PENDING = 'material-symbols:pending',
  INACTIVE = 'carbon:intent-request-inactive',
  EMPTY = 'mingcute:empty-box-line',
  TEST = 'mdi:test-tube',
  TEST_FAIL = 'mdi:test-tube-off',

  DOT = 'octicon:dot-24',
  FILTER = 'iconoir:filter',
  REALTIME = 'lets-icons:time-progress',
  TIMER_LEFT = 'fa6-solid:clock-rotate-left',
  CSV = 'ph:file-csv',
  NO_IMAGE = 'gridicons:image-remove',
  GRID = 'bitcoin-icons:grid-filled',
  LIST = 'material-symbols:list-rounded',
  CIRCLE = 'material-symbols:circle',
  BARS = 'fontisto:bar-chart',
  ARROWS = 'ph:arrows-left-right-bold',
  HUB = 'material-symbols:hub-outline',
  SHIELD_ALERT = 'si:shield-alert-duotone',
  CUBE = 'famicons:cube-outline',
  WARNING_CIRCLE = 'mingcute:warning-fill',
  CHECK_CIRCLE = 'lets-icons:check-fill',
  WORLD = 'mdi:world',
  UNREAD_MAILBOX = 'material-symbols:markunread-mailbox-outline',
  AREA_CHART = 'ic:outline-area-chart',
  CALENDAR_CLOCK = 'lucide:calendar-clock',

  SUN = 'material-symbols:wb-sunny-outline-rounded',
  MOON = 'basil:moon-outline',

  PROCESS = 'line-md:uploading-loop',
  VERIFIED = 'ph:seal-check-duotone',

  UPLOAD = 'duo-icons:upload-file',
}
